name: Cantú
favicon: null
layout_spectrum: 0.74659
typography_spectrum: 0.5546957997139543
title: Cantú
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77823805-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.004464318975806236
  lightness: 0.5712285721674562
  saturation: 0.375
  rhythmicContrast: 0.7097705793567002
purpose: []
