layout_spectrum: 0.5909895321719422
typography_spectrum: 0.8308474067844782
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.3598386767532418
  lightness: 0.4533180617317004
  saturation: 0.23485267514584238
  rhythmicContrast: 0.7763631370926442
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-77823805-1
  facebook: null
  twitter: null
author:
  name: Chris Cantu
  email: christopher.cantu@gmail.com
name: Cantú
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Github
    url: 'https://github.com/chriscantu'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/christophercantu'
    type: external
  - name: About Me
    id: e0440f82-ed38-4813-99de-28ba7c66c9cc
    type: content
favicon: null
title: Cantú
content: []
purpose: []
description: Chris Cantu's life and random interests
