name: Cantu
favicon: null
layout_spectrum: 0.716492333682254
typography_spectrum: 0.5546957997139543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.004464318975806236
  lightness: 0.5712285721674562
  saturation: 0.050984537694603205
  rhythmicContrast: 0.7097705793567002
purpose: []
