layout_spectrum: 0.18784992144009707
typography_spectrum: 0.8010974734565152
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6548213067515246
  lightness: 0.6812247990816832
  saturation: 0.547791167770577
  rhythmicContrast: 0.8837007522354327
name: Cantú
favicon: null
title: Cantú
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77823805-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
content: []
github: true
