typography_spectrum: 0.31558538408258396
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.11452467145877752
  lightness: 0.49618708869534556
  saturation: 0.9519457160061834
  rhythmicContrast: 0.20866755999458753
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7569709571774607
analytics:
  google: UA-77823805-1
  facebook: null
  twitter: null
author:
  name: Chris Cantu
  email: christopher.cantu@gmail.com
name: Cantú
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Github
    url: 'https://github.com/chriscantu'
    type: external
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/christophercantu'
    type: external
  - name: About Me
    id: e0440f82-ed38-4813-99de-28ba7c66c9cc
    type: content
  - name: '@chriscantu'
    url: 'https://twitter.com/chriscantu'
    type: external
favicon: null
title: Cantú
content: []
description: Chris Cantu's life and random interests
purpose: []
